### ISSUE TITLE
Throwing error in npm install trying to extract webviewer

### ISSUE THREAD

**Issue by vijay-joshi** [PDFTron/webviewer-vue-sample#8]
I cloned the repo and ran `npm install`.  webviewer download was successful but it threw error immediately after that.

Here is the error log:

```
 npx: installed 154 in 20.184s

Extracting to E:\aise hi\webviewer-vue-sample\public\lib

Downloading WebViewer... 100%
Download completed.

Extracting WebViewer...events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: invalid central directory file header signature: 0x0
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:258:70
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:631:5
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)
Emitted 'error' event at:
    at emitError (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:232:8)
    at emitErrorAndAutoClose (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:227:3)
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:258:42
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\yauzl\index.js:631:5
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\6432\node_modules\@pdftron\webviewer-downloader\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webviewer-vue-sample@0.1.0 download-webviewer: `npx @pdftron/webviewer-downloader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webviewer-vue-sample@0.1.0 download-webviewer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-13T07_29_25_646Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webviewer-vue-sample@0.1.0 postinstall: `npm run download-webviewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webviewer-vue-sample@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-13T07_29_25_683Z-debug.log

```

**Comment by andreysaf** [comment]
Hello @vijay-joshi,

Thanks for reaching out and letting us know of the issue. We have updated and fixed the issue. Please clone the repo and try again. 

Andrey
